# Site settings
title: Slackr Code
header-img: img/home-bg.jpg
email: hesham8@gmail.com
description: "code snippets, experiments, and general musings"
baseurl: ""
url: "http://slackr.me"
twitter_username: devilsacvodad
github_username:  hesham8

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
